### ISSUE TITLE
Add option to specify handorgel classes

### ISSUE THREAD

**Issue by JacobDB** [oncode/handorgel#10]
It'd be awesome if we could specify our own classes for each element of the handorgel instance. Something like:

```javascript
{
    containerClass: 'handorgel',
    headerClass: 'handorgel__header',
    buttonClass: 'handorgel__header__button',
    contentClass: 'handorgel__content',
    contentInnerClass: 'handorgel__content__inner',
}
```

Some notes:

- `containerClass` may not be necessary, because I think it's specified in the first parameter that gets passed.
- I'm not sure if all classes are 100% necessary as it is, so some of these may be pointless to add. If I recall correctly, I think only the container, button, and content elements are truly required, but I'll have to double check when I get moment.

If you'd like, I can look in to what it would take to implement and possibly submit a pull request.

**Comment by oncode** [comment]
Hi @JacobDB, I don't see a necessity for any of the classes to be configurable through the options. None of these classes are set with javascript. You can just change the markup and css to your desired classes. What do you think?

**Comment by JacobDB** [comment]
Oh maybe I assumed they where required for the script to work and they're actually not. I'll test it out tomorrow, thanks

**Comment by JacobDB** [comment]
You're right, I was able to get this working without using any of the standard classes. Closing this issue.
