### ISSUE TITLE
Close animation

### ISSUE THREAD

**Issue by fritzmg** [oncode/handorgel#27]
Currently Handorgel sets the `.handorgel__content` element to `height: auto` after the opening transition, presumably so that the wrapper's height will be correct when the viewport is resized etc.

However, this means there can't be a close animation as you cannot transition from `height: auto` to `height: 0`. Would it make sense to change Handorgel so that it does not set `height: auto` after the opening transition? Or am I missing something?

**Comment by oncode** [comment]
Before setting height to 0, the height is set to the current opened height. As you see on the demo page, it animates also when it's closed.

In code: https://github.com/oncode/handorgel/blob/master/src/js/fold.js#L115

**Comment by fritzmg** [comment]
Oh weird, sorry, then I need to investigate why it's not setting it to the current height in my case.
