### ISSUE TITLE
Initialize with opened fold

### ISSUE THREAD

**Issue by Mindless73** [oncode/handorgel#36]
We are using Handorgel in a legacy .net Web Forms application. So far it works perfectly, except if we want to have an open fold after a postback (or partial postback). 

We can open a fold with Accordion.folds[n].open(false) or with the data-open property, but the problem ist that the accordion gets initialized (with closed folds) after a postback and then we open the fold. This means there's a "blink" of the fold every time there is a postback.

Is there any way to initialize the accordion with an already opened fold?

**Comment by oncode** [comment]
Are you trying to avoid the initial transition? You can use `initialOpenTransition: false`option

**Comment by Mindless73** [comment]
We initialize the accordion with  initialOpenTransition: false and initialOpenTransitionDelay: 0

Here's how it looks:
![Test](https://github.com/user-attachments/assets/39925734-ddaf-426b-80f6-b161e788e8ed)
