### ISSUE TITLE
Auto Generate handorgel__header

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [oncode/handorgel#5]
It seems like it would make things a lot easier if the handorgel__header element could be auto generated based on the handorgel__content if it had a data-handorgel__header to specify the header text.

Have you considered this?

**Comment by oncode** [comment]
Unfortunately this won't be possible because the header markup depends on the site structure. It could be any hX element or an element with `aria-level` attribute (e.g. `<div aria-level="2"> ...</div>`)

**Comment by oncode** [comment]
Unfortunately this won't be possible because the header markup depends on the site structure. It could

**Comment by BebeSparkelSparkel** [comment]
I see. Thanks
